in RadioSite.unlock-route output error messages from rm(1) if any

diff --git a/lib/CommServer/RadioSite/unlock-route b/lib/CommServer/RadioSite/unlock-route
--- a/lib/CommServer/RadioSite/unlock-route
+++ b/lib/CommServer/RadioSite/unlock-route
@@ -20,16 +20,26 @@ test -e @LOCK || exit 3  # lock file does not exist
 test -s @LOCK || exit 2  # lock file is empty
 nodes=($(<@LOCK) .)
 locks=(${nodes[@]/%/\/@LOCK})
-rm -f ${locks[@]} || {
-    printf "failed to remove lock(s) for %s\n" "$(<@id)" >&2
-    for node in "${nodes[@]}"; do
-        test -e $node/@LOCK && 
-            printf "\t%s lock remains\n" "$(<$node/@id)" >&2
-    done
-    exit 1
-    }
 
-exit
+status=0
+while read rm_error; do
+    printf "unlock %s: %s\n" "$(<@id)" "$rm_error"
+    case "${rm_error##*: }" in
+
+        'No such file or directory')
+            # ignore this
+            ;;
+
+        'Is a directory')
+            status=1
+            ;;
+
+        *) status=1
+            ;;
+    esac
+done <<<"$(rm ${locks[@]} 2>&1)"
+
+exit $status
 
 NAME
     unlock-route
