edit CommServer.run to work toward in-process node lock checks, not complete...

diff --git a/lib/CommServer/run b/lib/CommServer/run
--- a/lib/CommServer/run
+++ b/lib/CommServer/run
@@ -104,43 +104,42 @@ check_node() { # see if node is available for connections, encode in a hash
     test ${node:0:1} != / && {
         # node is relative, so also check the absolute or canonical form:
         local canonical=$(readlink -f $node)
-        test -n ${available[$canonical]} || check_node $canonical # recurse!
+        printf "\tcanonical: %s\n" "$canonical" >> $debugfile
+        test -n "${available[$canonical]}" || check_node $canonical # recurse!
         available[$node]=${available[$canonical]}
-        test "$ready" == y && return 0 # note that global 'ready' was set in recursed fn
+        test "${available[$node]}" == y && return 0
         return 1
         }
     # node is absolute, so check the node attributes and store y or n:
-    ready=n
-    test -e $node/radio-power=ON -a ! -e $node/@LOCK && ready=y
-    available[$node]=$ready
-    test $ready == y && return 0
-    return 1
+    test -e $node/radio-power=ON -a ! -e $node/@LOCK && available[$node]=y && return 0
+    available[$node]=n && return 1
     }
 
-choose_route() { # given a site, find an available route
+choose_route() { # given a site, find first available route
     site=$1
+    test -e $site/@routes || return 2 ## return value 2 means: no routes defined for site
     echo choose_route $site >> $debugfile
     case ${available[$site]} in
         y)  true;;
         n)  false;;
-        '') check_node $site || false
+        '') check_node $site;;
     esac || return 1
-    ## assert: the site is powered and not locked, so iterate its @routes list to find a route
+    ## assert: the site is powered and not locked, so iterate on its @routes list
     local max_hops=$max_hops
     test -e $site/@max-hops && max_hops=$(<$site/@max-hops) ## bad! should check tob attribute...
-    test -e $site/@routes || return 2 ## return value 2 means: no routes defined for site
     ## 
     unset route
-    while read -a rt; do
-        ${#rt[@]} -gt $max_hops && continue # too many hops, try next route ...
-        for node in ${rt[@]}; do
+    while read -a rte; do
+        test ${#rte[@]} -gt $max_hops && continue # too many hops, try next route ...
+        for node in ${rte[@]}; do
             case ${available[$node]} in
-                n)  continue 2;;
-                '') check_node $node || continue 2
-            esac
+                y)  true;;
+                n)  false;;
+                '') check_node $node
+            esac || continue 2
         done
         ## assert: all nodes in this route are available
-        route=(${rt[@]}) # chosen route is in array variable route
+        route=(${rte[@]}) # chosen route is in global array variable route
         return 0
     done < $site/@routes
     return 1
@@ -169,6 +168,7 @@ process_queue() { # return value: 0 if empty, else 1
         # aquire a route or skip this site:
         if test "$use_lock_route" == 1; then
             route=$($tob $tsite.lock-route --release probe)
+            test -n "$route" || continue
         else
             test -n "${available[$site]}" || check_node $site
             test "${available[$site]}" == y || continue
